security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory:
        users:
          technicien:
            password: '$2y$13$M0F/xI6/IdfdEVCDTvNos.Wkq2D0Q88F0hibkFqtqExHoo/hyLlhe'
            roles: 'ROLE_TECHNICIEN'
          chargemission:
            password: '$2y$13$4UhKfZ2Zxf.vhtib2HJ7Ke0kgMZBhmZTBcIbJIGLHQS3b4JmDSiRu'
            roles: 'ROLE_CHARGEMISSION'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: in_memory
      form_login:
        login_path: app_connexion
        check_path: app_connexion
      logout:
        path: app_deconnexion
        target: app_connexion

  # Contrôle d'accès basé sur les rôles
  access_control:
    - { path: ^/charge-de-mission, roles: ROLE_CHARGEMISSION }
    - { path: ^/technicien, roles: ROLE_TECHNICIEN }
    - { path: ^/connexion$, roles: ACCES_PUBLIC }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10